### ISSUE TITLE
NullRef

### ISSUE THREAD

**Issue by Saishy** [ByronMayne/Weaver#1]
![unity_2017-11-28_22-58-25](https://user-images.githubusercontent.com/2012108/33352379-baca1374-d48f-11e7-95c4-c17e59102f14.png)

On opening the project with Unity 2017.2.0f3

**Comment by ByronMayne** [comment]
It's odd because that class is serialized. What I did do was assign the log a default value so this should not happen anymore. 

I would also suggest you pull I had to do a bunch of fixes for 2017 (which are backwards compatible).
