### ISSUE TITLE
Which type of license does this project use?

### ISSUE THREAD

**Issue by z3nth10n** [ByronMayne/Weaver#19]
I need to use this on a paid asset and I would like to know if I'm allowed to include this on my project. **Thanks!**

**EDIT:** I just realized that in the bottom of the `README` the *MIT License* is advertised, but could you include a `LICENSE` file. Just to clarify.

**Comment by ByronMayne** [comment]
Hey Z3nth10n,

Feel free to included it in your paid asset. 

Cheers,
Byron
