### ISSUE TITLE
NotSupportedException occurs

### ISSUE THREAD

**Issue by judaigi** [ByronMayne/Weaver#22]
I am very glad to find Weaver for my project.
But, I had so many same exceptions.
```
NotSupportedException: The invoked member is not supported in a dynamic module.
System.Reflection.Emit.AssemblyBuilder.get_Location () (at <567df3e0919241ba98db88bec4c6696f>:0)
Weaver.WeaverAssemblyResolver..ctor () (at Assets/AssetStore/Weaver/Editor/Resolver/WeaverAssemblyResolver.cs:39)
Weaver.WeaverSettings.GetReaderParameters () (at Assets/AssetStore/Weaver/Editor/Settings/WeaverSettings.cs:193)
Weaver.WeaverSettings.WeaveAssembly (System.String assemblyPath) (at Assets/AssetStore/Weaver/Editor/Settings/WeaverSettings.cs:250)
```

When resolving location of dynamic modules, for example,

```Assembly: Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null```

I modified the line below at WeaverAssemblyResolver() constructor to solve the problem temporally.
```
if (assembly.ReflectionOnly)
```
```
if (assembly.ReflectionOnly || assembly.IsDynamic)
```

**Comment by ByronMayne** [comment]
Hey Judaigi,

I appreciate you taking the time to file a bug for this since it will help others. I can create a patch for the current version with you suggested changes. 

I will also port it over the the new version of Weaver which I am creating in another branch.

Thanks,
Byron

**Comment by ByronMayne** [comment]
Fixed in current branch :)
