### ISSUE TITLE
Missing references to Mono.Cecil 

### ISSUE THREAD

**Issue by krisrok** [ByronMayne/Weaver#23]
Seems Unity changed once again how it includes the Mono.Cecil stuff. We cannot reference the dlls anymore by asmdef. 
Because you updated the API to the newer version of cecil we cannot use the dlls from this repository's history.

So I just grabbed them from the Unity folder (`Editor\Data\il2cpp\build\deploy\net471` in this case) and put them into the Lib folder where you had them before, works fine.

This is an issue at least with 2019.4 (and i guess 2019.3).

**Comment by esselasy** [comment]
It works with 2019.3.14f1.

But when I removed "com.unity.multiplayer-hlapi": "1.0.4" from manifest.json, Mono.Cecil also disappeared.

**Comment by krisrok** [comment]
Yes, my mistake. I didn‘t pay attention to the packages manifest. Was not aware there is a Cecil package.
