### ISSUE TITLE
Script won't update after first successful weaving

### ISSUE THREAD

**Issue by Catchawink** [ByronMayne/Weaver#24]
I'm using Assembly Definitions within Unity and created a custom weaving component to weave specific assemblies. For some reason, if I add a field to a type in an assembly using my component, and the type of the field is a delegate type that I've defined, scripts in the assembly don't appear to update after the first successful modification/weaving.

The following code runs correctly every time I recompile, but if I attempt to replace PropertyChangedEventHandler with a custom delegate type, the assembly compiles and weaves correctly only once, then refuses to compile/update with newer script changes. It only works again if I restart Unity. I'm not receiving any error messages:
```

var handlerReference = typeDefinition.Module.ImportReference(typeof(System.ComponentModel.PropertyChangedEventHandler));
 
var fieldDef = new FieldDefinition(nameof(INotifyMethodCalled.MethodCalled), FieldAttributes.Private | FieldAttributes.NotSerialized, handlerReference);

typeDefinition.Fields.Add(fieldDef);
```
Any help would be greatly appreciated.

**Comment by Catchawink** [comment]
I just resolved my issue--the script doing the weaving was referencing the assembly it was weaving. This was the programmatic equivalent of a snake eating its tail and choking on it. The script using Mono.Cecil no longer references its target assembly.

**Comment by ByronMayne** [comment]
haha I am glad you figured it out.
