### ISSUE TITLE
Debug Symbols are not written to disk breaking call stacks. 

### ISSUE THREAD

**Issue by Saishy** [ByronMayne/Weaver#3]
Merely having the Weaver set to "run automatically" will throw all your call stacks into a chaos, making any bug you find point to the wrong line or file, also impossible to debug since the debugger will send you to the wrong place.

**Comment by ByronMayne** [comment]
Oh okay that is not to hard to fix :) 

I currently have Weaver reading the debug symbols (.mdb) which will give you the correct call stack if an error happens while waving but I never said to write them as well.
