### ISSUE TITLE
Does this work with IL2CPP?

### ISSUE THREAD

**Issue by Claytonious** [ByronMayne/Weaver#4]
If the scripting backend for a Unity project is IL2CPP, does your Weaver still work?

Thanks - and super interesting project!

**Comment by ByronMayne** [comment]
Hey there,
IL2CPP takes the MSIL (Microsoft Intermediate Language) and turns it into C++.  This project edits the MSIL every time the dlls are generated and after a build but before IL2CPP takes a turn. 

So long story short yes this does work with IL2CPP!
